export const userConstants = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',

  GETALL_REQUEST: 'USERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'USERS_GETALL_FAILURE',

  DELETE_REQUEST: 'USERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'USERS_DELETE_FAILURE',

  FETCH_EVENTS_PENDING: 'FETCH_EVENTS_PENDING',
  FETCH_EVENTS_SUCCESS: 'FETCH_EVENTS_SUCCESS',
  FETCH_EVENTS_ERROR: 'FETCH_EVENTS_ERROR',

  FETCH_TIMETABLE_PENDING: 'FETCH_TIMETABLE_PENDING',
  FETCH_TIMETABLE_SUCCESS: 'FETCH_TIMETABLE_SUCCESS',
  FETCH_TIMETABLE_ERROR: 'FETCH_TIMETABLE_ERROR',

  FETCH_JOURNAL_PENDING: 'FETCH_JOURNAL_PENDING',
  FETCH_JOURNAL_SUCCESS: 'FETCH_JOURNAL_SUCCESS',
  FETCH_JOURNAL_ERROR: 'FETCH_JOURNAL_ERROR',
}