export const userConstants = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',

  GETALL_REQUEST: 'USERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'USERS_GETALL_FAILURE',

  DELETE_REQUEST: 'USERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'USERS_DELETE_FAILURE',

  FETCH_EVENTS_PENDING: 'FETCH_EVENTS_PENDING',
  FETCH_EVENTS_SUCCESS: 'FETCH_EVENTS_SUCCESS',
  FETCH_EVENTS_ERROR: 'FETCH_EVENTS_ERROR',

  FETCH_TIMETABLE_PENDING: 'FETCH_TIMETABLE_PENDING',
  FETCH_TIMETABLE_SUCCESS: 'FETCH_TIMETABLE_SUCCESS',
  FETCH_TIMETABLE_ERROR: 'FETCH_TIMETABLE_ERROR',

  FETCH_JOURNAL_PENDING: 'FETCH_JOURNAL_PENDING',
  FETCH_JOURNAL_SUCCESS: 'FETCH_JOURNAL_SUCCESS',
  FETCH_JOURNAL_ERROR: 'FETCH_JOURNAL_ERROR',

  FETCH_SUBHEADER_PENDING: 'FETCH_SUBHEADER_PENDING',
  FETCH_SUBHEADER_SUCCESS: 'FETCH_SUBHEADER_SUCCESS',
  FETCH_SUBHEADER_ERROR: 'FETCH_SUBHEADER_ERROR',

  FETCH_HEADER_PENDING: 'FETCH_HEADER_PENDING',
  FETCH_HEADER_SUCCESS: 'FETCH_HEADER_SUCCESS',
  FETCH_HEADER_ERROR: 'FETCH_HEADER_ERROR',

  FETCH_ACCOUNT_PENDING: 'FETCH_ACCOUNT_PENDING',
  FETCH_ACCOUNT_SUCCESS: 'FETCH_ACCOUNT_SUCCESS',
  FETCH_ACCOUNT_ERROR: 'FETCH_ACCOUNT_ERROR',
}